import { describe, it, expect } from "vitest";
import {
  role,
  staffRole,
  companyKind,
  membershipStatus,
  invitationKind,
  invitationStatus,
  tenantKind,
  ownerMandateStatus,
  propertyKind,
  unitUse,
  unitKind,
  unitStatus,
  occupantRelationship,
  contractStatus,
  contractOrigin,
  contractCancelKind,
  contractEndReason,
  contractVersionKind,
  termPhase,
  approvalSlot,
  approvalKind,
  approvalStatus,
  tawtheeqPath,
  tawtheeqWorkflowState,
  tawtheeqPortalStatus,
  discrepancyClass,
  discrepancyResolution,
  discrepancyStatus,
  handoverKind,
  instalmentStatus,
  chequeStatus,
  paymentMethod,
  paymentSource,
  paymentStatus,
  allocationStatus,
  paymentReversalReason,
  chargeKind,
  chargePayer,
  chargeStatus,
  depositStatus,
  invoiceStatus,
  invoiceRecipientType,
  numberSeries,
  receiptStatus,
  ownerStatementStatus,
  ticketStatus,
  ticketCategory,
  ticketPriority,
  costPayer,
  quoteStatus,
  dispatchStatus,
  documentType,
  documentSensitivity,
  documentProcessingStatus,
  documentReviewStatus,
  documentValidity,
  noteVisibility,
  taskStatus,
  reminderStatus,
  notificationChannel,
  notificationStatus,
  draftedActionStatus,
  initiator,
  channel,
  fieldProvenance,
} from "./index";

const vocabulary = [
  {
    name: "role",
    schema: role,
    values: [
      "manager",
      "owner",
      "tenant",
      "technician",
      "company_administrator",
      "accountant",
    ],
    count: 6,
  },
  {
    name: "staffRole",
    schema: staffRole,
    values: ["manager", "technician", "company_administrator", "accountant"],
    count: 4,
  },
  {
    name: "companyKind",
    schema: companyKind,
    values: ["management_company", "self_managed_owner"],
    count: 2,
  },
  {
    name: "membershipStatus",
    schema: membershipStatus,
    values: ["invited", "active", "suspended", "removed"],
    count: 4,
  },
  {
    name: "invitationKind",
    schema: invitationKind,
    values: ["staff", "owner", "tenant"],
    count: 3,
  },
  {
    name: "invitationStatus",
    schema: invitationStatus,
    values: ["pending", "accepted", "expired", "revoked"],
    count: 4,
  },
  {
    name: "tenantKind",
    schema: tenantKind,
    values: ["individual", "company", "government", "diplomatic"],
    count: 4,
  },
  {
    name: "ownerMandateStatus",
    schema: ownerMandateStatus,
    values: ["active", "expired", "ended"],
    count: 3,
  },
  {
    name: "propertyKind",
    schema: propertyKind,
    values: ["building", "villa", "plot"],
    count: 3,
  },
  {
    name: "unitUse",
    schema: unitUse,
    values: ["residential", "commercial"],
    count: 2,
  },
  {
    name: "unitKind",
    schema: unitKind,
    values: [
      "apartment",
      "villa",
      "townhouse",
      "office",
      "shop",
      "warehouse",
      "other",
    ],
    count: 7,
  },
  {
    name: "unitStatus",
    schema: unitStatus,
    values: [
      "vacant",
      "listed",
      "reserved",
      "occupied",
      "notice_given",
      "under_maintenance",
      "blocked",
    ],
    count: 7,
  },
  {
    name: "occupantRelationship",
    schema: occupantRelationship,
    values: [
      "spouse",
      "child",
      "parent",
      "relative",
      "domestic_worker",
      "other",
    ],
    count: 6,
  },
  {
    name: "contractStatus",
    schema: contractStatus,
    values: [
      "draft",
      "awaiting_owner_approval",
      "awaiting_tenant_acceptance",
      "concluded",
      "ended",
      "cancelled",
    ],
    count: 6,
  },
  {
    name: "contractOrigin",
    schema: contractOrigin,
    values: ["app", "retroactive"],
    count: 2,
  },
  {
    name: "contractCancelKind",
    schema: contractCancelKind,
    values: [
      "withdrawn_by_manager",
      "returned_by_owner",
      "returned_by_tenant",
      "cancelled_draft",
    ],
    count: 4,
  },
  {
    name: "contractEndReason",
    schema: contractEndReason,
    values: [
      "expired",
      "renewed",
      "terminated_by_notice",
      "terminated_by_agreement",
      "terminated_by_court_order",
      "cancelled_on_portal",
    ],
    count: 6,
  },
  {
    name: "contractVersionKind",
    schema: contractVersionKind,
    values: ["standard", "tawtheeq_adoption"],
    count: 2,
  },
  {
    name: "termPhase",
    schema: termPhase,
    values: [
      "upcoming",
      "current",
      "renewal_window",
      "notice_deadline_passed",
      "holding_over",
    ],
    count: 5,
  },
  {
    name: "approvalSlot",
    schema: approvalSlot,
    values: ["manager", "owner", "tenant"],
    count: 3,
  },
  {
    name: "approvalKind",
    schema: approvalKind,
    values: [
      "contract_approval",
      "owner_reapproval",
      "skip_confirmation",
      "cost_approval",
      "retroactive_confirmation",
    ],
    count: 5,
  },
  {
    name: "approvalStatus",
    schema: approvalStatus,
    values: ["requested", "approved", "returned", "voided"],
    count: 4,
  },
  {
    name: "tawtheeqPath",
    schema: tawtheeqPath,
    values: ["normal", "skip", "retroactive"],
    count: 3,
  },
  {
    name: "tawtheeqWorkflowState",
    schema: tawtheeqWorkflowState,
    values: [
      "awaiting_registration",
      "submitted_on_portal",
      "under_review",
      "discrepancies_open",
      "awaiting_owner_reapproval",
      "registered",
      "skipped",
      "closed",
    ],
    count: 8,
  },
  {
    name: "tawtheeqPortalStatus",
    schema: tawtheeqPortalStatus,
    values: [
      "not_started",
      "pending",
      "registered",
      "renewed",
      "skipped",
      "cancelled",
    ],
    count: 6,
  },
  {
    name: "discrepancyClass",
    schema: discrepancyClass,
    values: ["identity", "material", "minor"],
    count: 3,
  },
  {
    name: "discrepancyResolution",
    schema: discrepancyResolution,
    values: ["adopt", "cancel_and_reregister", "mark_equivalent"],
    count: 3,
  },
  {
    name: "discrepancyStatus",
    schema: discrepancyStatus,
    values: ["open", "resolved"],
    count: 2,
  },
  {
    name: "handoverKind",
    schema: handoverKind,
    values: ["move_in", "move_out"],
    count: 2,
  },
  {
    name: "instalmentStatus",
    schema: instalmentStatus,
    values: ["open", "partly_paid", "paid", "waived", "cancelled"],
    count: 5,
  },
  {
    name: "chequeStatus",
    schema: chequeStatus,
    values: [
      "pending",
      "received",
      "deposited",
      "cleared",
      "partly_paid",
      "bounced",
      "replaced",
      "returned_to_drawer",
    ],
    count: 8,
  },
  {
    name: "paymentMethod",
    schema: paymentMethod,
    values: ["cash", "transfer", "cheque", "card_elsewhere"],
    count: 4,
  },
  {
    name: "paymentSource",
    schema: paymentSource,
    values: ["app", "external"],
    count: 2,
  },
  {
    name: "paymentStatus",
    schema: paymentStatus,
    values: ["recorded", "reversed"],
    count: 2,
  },
  {
    name: "allocationStatus",
    schema: allocationStatus,
    values: ["active", "voided"],
    count: 2,
  },
  {
    name: "paymentReversalReason",
    schema: paymentReversalReason,
    values: ["bounced", "recorded_in_error"],
    count: 2,
  },
  {
    name: "chargeKind",
    schema: chargeKind,
    values: ["maintenance", "utility", "penalty", "fee", "other"],
    count: 5,
  },
  {
    name: "chargePayer",
    schema: chargePayer,
    values: ["owner", "tenant", "company"],
    count: 3,
  },
  {
    name: "chargeStatus",
    schema: chargeStatus,
    values: ["open", "invoiced", "settled", "waived", "cancelled"],
    count: 5,
  },
  {
    name: "depositStatus",
    schema: depositStatus,
    values: [
      "expected",
      "held",
      "refund_due",
      "refunded",
      "applied",
      "carried_over",
    ],
    count: 6,
  },
  {
    name: "invoiceStatus",
    schema: invoiceStatus,
    values: ["draft", "issued", "partly_paid", "paid", "credited"],
    count: 5,
  },
  {
    name: "invoiceRecipientType",
    schema: invoiceRecipientType,
    values: ["tenant", "owner"],
    count: 2,
  },
  {
    name: "numberSeries",
    schema: numberSeries,
    values: ["INV", "CN", "RCPT", "STMT"],
    count: 4,
  },
  {
    name: "receiptStatus",
    schema: receiptStatus,
    values: ["issued", "voided"],
    count: 2,
  },
  {
    name: "ownerStatementStatus",
    schema: ownerStatementStatus,
    values: ["draft", "in_review", "issued", "superseded"],
    count: 4,
  },
  {
    name: "ticketStatus",
    schema: ticketStatus,
    values: [
      "reported",
      "triaged",
      "awaiting_quote",
      "awaiting_cost_approval",
      "scheduled",
      "in_progress",
      "on_hold",
      "work_completed",
      "closed",
      "cancelled",
    ],
    count: 10,
  },
  {
    name: "ticketCategory",
    schema: ticketCategory,
    values: [
      "ac",
      "plumbing",
      "electrical",
      "appliances",
      "pest_control",
      "cleaning",
      "carpentry",
      "painting",
      "lift",
      "fire_safety",
      "other",
    ],
    count: 11,
  },
  {
    name: "ticketPriority",
    schema: ticketPriority,
    values: ["emergency", "urgent", "routine"],
    count: 3,
  },
  {
    name: "costPayer",
    schema: costPayer,
    values: ["owner", "tenant", "company", "split"],
    count: 4,
  },
  {
    name: "quoteStatus",
    schema: quoteStatus,
    values: ["requested", "received", "approved", "rejected"],
    count: 4,
  },
  {
    name: "dispatchStatus",
    schema: dispatchStatus,
    values: ["assigned", "accepted", "declined", "done", "cancelled"],
    count: 5,
  },
  {
    name: "documentType",
    schema: documentType,
    values: [
      "emirates_id",
      "passport",
      "title_deed",
      "site_plan",
      "management_agreement",
      "tawtheeq_authorisation",
      "trade_licence",
      "signatory_id",
      "civil_defence_certificate",
      "hassantuk_certificate",
      "floor_plan",
      "maintenance_contract",
      "fire_safety_contract",
      "income_evidence",
      "occupancy_certificate",
      "tawtheeq",
      "contract",
      "receipt",
      "invoice",
      "quote",
      "transfer_slip",
      "cheque_image",
      "portal_summary",
      "photo",
      "voice_note",
      "video",
      "other",
    ],
    count: 27,
  },
  {
    name: "documentSensitivity",
    schema: documentSensitivity,
    values: ["identity", "financial", "general"],
    count: 3,
  },
  {
    name: "documentProcessingStatus",
    schema: documentProcessingStatus,
    values: [
      "awaiting_upload",
      "uploaded",
      "scan_clean",
      "scan_rejected",
      "extracting",
      "extracted",
      "extraction_failed",
    ],
    count: 7,
  },
  {
    name: "documentReviewStatus",
    schema: documentReviewStatus,
    values: ["pending_review", "accepted", "rejected", "superseded"],
    count: 4,
  },
  {
    name: "documentValidity",
    schema: documentValidity,
    values: ["valid", "expiring_soon", "expired"],
    count: 3,
  },
  {
    name: "noteVisibility",
    schema: noteVisibility,
    values: ["staff", "parties"],
    count: 2,
  },
  {
    name: "taskStatus",
    schema: taskStatus,
    values: ["open", "done", "cancelled"],
    count: 3,
  },
  {
    name: "reminderStatus",
    schema: reminderStatus,
    values: ["scheduled", "fired", "dismissed"],
    count: 3,
  },
  {
    name: "notificationChannel",
    schema: notificationChannel,
    values: ["in_app", "email", "push"],
    count: 3,
  },
  {
    name: "notificationStatus",
    schema: notificationStatus,
    values: ["queued", "sent", "failed"],
    count: 3,
  },
  {
    name: "draftedActionStatus",
    schema: draftedActionStatus,
    values: ["drafting", "ready", "committed", "rejected", "expired", "failed"],
    count: 6,
  },
  {
    name: "initiator",
    schema: initiator,
    values: ["person", "co_worker", "pipeline", "scheduler"],
    count: 4,
  },
  {
    name: "channel",
    schema: channel,
    values: ["web_form", "mobile_form", "chat", "voice", "system", "import"],
    count: 6,
  },
  {
    name: "fieldProvenance",
    schema: fieldProvenance,
    values: ["ai_confirmed", "ai_edited", "human_entered"],
    count: 3,
  },
] as const;

describe("closed vocabulary", () => {
  it.each(vocabulary)(
    "preserves the specified values for $name",
    ({ schema, values }) => {
      expect(schema.options).toEqual(values);
    },
  );
  it.each(vocabulary)(
    "preserves the specified count for $name",
    ({ schema, count }) => {
      expect(schema.options).toHaveLength(count);
    },
  );
  it.each(vocabulary)("has no repeated values for $name", ({ schema }) => {
    expect(new Set(schema.options).size).toBe(schema.options.length);
  });
  it.each(vocabulary.filter(({ name }) => name !== "numberSeries"))(
    "stores snake case values for $name",
    ({ schema }) => {
      expect(
        schema.options.every((value) => /^[a-z][a-z0-9_]*$/.test(value)),
      ).toBe(true);
    },
  );
  it.each(vocabulary)("refuses an unknown value for $name", ({ schema }) => {
    expect(schema.safeParse("unknown_value").success).toBe(false);
  });
  it("uses uppercase document number prefixes", () => {
    expect(numberSeries.options.every((value) => /^[A-Z]+$/.test(value))).toBe(
      true,
    );
  });
});
