import type { statusTones } from "@aqarak/ui-tokens";
import type { StatusTagProps } from "@/components/system/status-catalogue";
type ExpectedStatus = StatusTagProps & {
  english: string;
  arabic: string;
  tone: keyof typeof statusTones;
};
/** Wording and tones fixed by the design contract, independent of the runtime catalogues. */
export const expectedStatuses = [
  {
    entity: "unit",
    state: "vacant",
    english: "Vacant",
    arabic: "شاغرة",
    tone: "neutral",
  },
  {
    entity: "unit",
    state: "listed",
    english: "Listed",
    arabic: "معروضة",
    tone: "progress",
  },
  {
    entity: "unit",
    state: "reserved",
    english: "Reserved",
    arabic: "محجوزة",
    tone: "attention",
  },
  {
    entity: "unit",
    state: "occupied",
    english: "Occupied",
    arabic: "مؤجرة",
    tone: "success",
  },
  {
    entity: "unit",
    state: "notice_given",
    english: "Notice given",
    arabic: "تم الإخطار بالإخلاء",
    tone: "attention",
  },
  {
    entity: "unit",
    state: "under_maintenance",
    english: "Under maintenance",
    arabic: "تحت الصيانة",
    tone: "progress",
  },
  {
    entity: "unit",
    state: "blocked",
    english: "Blocked",
    arabic: "موقوفة",
    tone: "danger",
  },
  {
    entity: "contract",
    state: "draft",
    english: "Draft",
    arabic: "مسودة",
    tone: "neutral",
  },
  {
    entity: "contract",
    state: "awaiting_owner_approval",
    english: "Awaiting owner approval",
    arabic: "بانتظار موافقة المالك",
    tone: "attention",
  },
  {
    entity: "contract",
    state: "awaiting_tenant_acceptance",
    english: "Awaiting tenant acceptance",
    arabic: "بانتظار قبول المستأجر",
    tone: "attention",
  },
  {
    entity: "contract",
    state: "concluded",
    english: "Concluded",
    arabic: "مبرم",
    tone: "success",
  },
  {
    entity: "contract",
    state: "ended",
    english: "Ended",
    arabic: "منتهي",
    tone: "muted",
  },
  {
    entity: "contract",
    state: "cancelled",
    english: "Cancelled",
    arabic: "ملغى",
    tone: "muted",
  },
  {
    entity: "tawtheeq_record",
    state: "awaiting_registration",
    english: "Awaiting registration",
    arabic: "بانتظار التوثيق",
    tone: "attention",
  },
  {
    entity: "tawtheeq_record",
    state: "submitted_on_portal",
    english: "Submitted on portal",
    arabic: "مقدم في البوابة",
    tone: "progress",
  },
  {
    entity: "tawtheeq_record",
    state: "under_review",
    english: "Under review",
    arabic: "قيد المطابقة",
    tone: "progress",
  },
  {
    entity: "tawtheeq_record",
    state: "discrepancies_open",
    english: "Discrepancies open",
    arabic: "اختلافات قيد المعالجة",
    tone: "danger",
  },
  {
    entity: "tawtheeq_record",
    state: "awaiting_owner_reapproval",
    english: "Awaiting owner re-approval",
    arabic: "بانتظار إعادة موافقة المالك",
    tone: "attention",
  },
  {
    entity: "tawtheeq_record",
    state: "registered",
    english: "Registered",
    arabic: "موثق",
    tone: "success",
  },
  {
    entity: "tawtheeq_record",
    state: "skipped",
    english: "Skipped",
    arabic: "بدون توثيق",
    tone: "muted",
  },
  {
    entity: "tawtheeq_record",
    state: "closed",
    english: "Closed",
    arabic: "مغلق في البوابة",
    tone: "muted",
  },
  {
    entity: "instalment",
    state: "open",
    english: "Open",
    arabic: "غير مسدد",
    tone: "neutral",
  },
  {
    entity: "instalment",
    state: "partly_paid",
    english: "Partly paid",
    arabic: "مسدد جزئياً",
    tone: "attention",
  },
  {
    entity: "instalment",
    state: "paid",
    english: "Paid",
    arabic: "مسدد",
    tone: "success",
  },
  {
    entity: "instalment",
    state: "waived",
    english: "Waived",
    arabic: "معفى",
    tone: "muted",
  },
  {
    entity: "instalment",
    state: "cancelled",
    english: "Cancelled",
    arabic: "ملغى",
    tone: "muted",
  },
  {
    entity: "cheque",
    state: "pending",
    english: "Pending",
    arabic: "بانتظار الاستلام",
    tone: "neutral",
  },
  {
    entity: "cheque",
    state: "received",
    english: "Received",
    arabic: "مستلم",
    tone: "progress",
  },
  {
    entity: "cheque",
    state: "deposited",
    english: "Deposited",
    arabic: "مودع",
    tone: "progress",
  },
  {
    entity: "cheque",
    state: "cleared",
    english: "Cleared",
    arabic: "محصل",
    tone: "success",
  },
  {
    entity: "cheque",
    state: "partly_paid",
    english: "Partly paid",
    arabic: "مدفوع جزئياً",
    tone: "attention",
  },
  {
    entity: "cheque",
    state: "bounced",
    english: "Bounced",
    arabic: "مرتجع",
    tone: "danger",
  },
  {
    entity: "cheque",
    state: "replaced",
    english: "Replaced",
    arabic: "مستبدل",
    tone: "muted",
  },
  {
    entity: "cheque",
    state: "returned_to_drawer",
    english: "Returned to drawer",
    arabic: "معاد للساحب",
    tone: "muted",
  },
  {
    entity: "invoice",
    state: "draft",
    english: "Draft",
    arabic: "مسودة",
    tone: "neutral",
  },
  {
    entity: "invoice",
    state: "issued",
    english: "Issued",
    arabic: "صادرة",
    tone: "progress",
  },
  {
    entity: "invoice",
    state: "partly_paid",
    english: "Partly paid",
    arabic: "مسددة جزئياً",
    tone: "attention",
  },
  {
    entity: "invoice",
    state: "paid",
    english: "Paid",
    arabic: "مسددة",
    tone: "success",
  },
  {
    entity: "invoice",
    state: "credited",
    english: "Credited",
    arabic: "ملغاة بإشعار دائن",
    tone: "muted",
  },
  {
    entity: "receipt",
    state: "issued",
    english: "Issued",
    arabic: "صادر",
    tone: "success",
  },
  {
    entity: "receipt",
    state: "voided",
    english: "Voided",
    arabic: "ملغى",
    tone: "muted",
  },
  {
    entity: "ticket",
    state: "reported",
    english: "Reported",
    arabic: "تم الإبلاغ",
    tone: "neutral",
  },
  {
    entity: "ticket",
    state: "triaged",
    english: "Triaged",
    arabic: "تم الفرز",
    tone: "progress",
  },
  {
    entity: "ticket",
    state: "awaiting_quote",
    english: "Awaiting quote",
    arabic: "بانتظار عرض السعر",
    tone: "attention",
  },
  {
    entity: "ticket",
    state: "awaiting_cost_approval",
    english: "Awaiting cost approval",
    arabic: "بانتظار اعتماد التكلفة",
    tone: "attention",
  },
  {
    entity: "ticket",
    state: "scheduled",
    english: "Scheduled",
    arabic: "مجدول",
    tone: "progress",
  },
  {
    entity: "ticket",
    state: "in_progress",
    english: "In progress",
    arabic: "قيد التنفيذ",
    tone: "progress",
  },
  {
    entity: "ticket",
    state: "on_hold",
    english: "On hold",
    arabic: "معلق",
    tone: "attention",
  },
  {
    entity: "ticket",
    state: "work_completed",
    english: "Work completed",
    arabic: "تم الإنجاز",
    tone: "success",
  },
  {
    entity: "ticket",
    state: "closed",
    english: "Closed",
    arabic: "مغلق",
    tone: "muted",
  },
  {
    entity: "ticket",
    state: "cancelled",
    english: "Cancelled",
    arabic: "ملغى",
    tone: "muted",
  },
  {
    entity: "document_version",
    state: "pending_review",
    english: "Pending review",
    arabic: "بانتظار المراجعة",
    tone: "attention",
  },
  {
    entity: "document_version",
    state: "accepted",
    english: "Accepted",
    arabic: "معتمد",
    tone: "success",
  },
  {
    entity: "document_version",
    state: "rejected",
    english: "Rejected",
    arabic: "مرفوض",
    tone: "danger",
  },
  {
    entity: "document_version",
    state: "superseded",
    english: "Superseded",
    arabic: "مستبدل",
    tone: "muted",
  },
  {
    entity: "drafted_action",
    state: "drafting",
    english: "Drafting",
    arabic: "قيد الإعداد",
    tone: "progress",
  },
  {
    entity: "drafted_action",
    state: "ready",
    english: "Ready",
    arabic: "بانتظار التأكيد",
    tone: "attention",
  },
  {
    entity: "drafted_action",
    state: "committed",
    english: "Committed",
    arabic: "منفذ",
    tone: "success",
  },
  {
    entity: "drafted_action",
    state: "rejected",
    english: "Rejected",
    arabic: "مرفوض",
    tone: "muted",
  },
  {
    entity: "drafted_action",
    state: "expired",
    english: "Expired",
    arabic: "منتهي الصلاحية",
    tone: "muted",
  },
  {
    entity: "drafted_action",
    state: "failed",
    english: "Failed",
    arabic: "فشل التنفيذ",
    tone: "danger",
  },
  {
    entity: "approval",
    state: "requested",
    english: "Requested",
    arabic: "مطلوبة",
    tone: "attention",
  },
  {
    entity: "approval",
    state: "approved",
    english: "Approved",
    arabic: "موافق عليها",
    tone: "success",
  },
  {
    entity: "approval",
    state: "changes_requested",
    english: "Changes requested",
    arabic: "مطلوب تعديل",
    tone: "danger",
  },
  {
    entity: "approval",
    state: "voided",
    english: "Voided",
    arabic: "ملغاة",
    tone: "muted",
  },
  {
    entity: "membership",
    state: "invited",
    english: "Invited",
    arabic: "مدعو",
    tone: "attention",
  },
  {
    entity: "membership",
    state: "active",
    english: "Active",
    arabic: "نشط",
    tone: "success",
  },
  {
    entity: "membership",
    state: "suspended",
    english: "Suspended",
    arabic: "موقوف",
    tone: "danger",
  },
  {
    entity: "membership",
    state: "removed",
    english: "Removed",
    arabic: "منتهي",
    tone: "muted",
  },
  {
    entity: "invitation",
    state: "pending",
    english: "Pending",
    arabic: "معلقة",
    tone: "attention",
  },
  {
    entity: "invitation",
    state: "accepted",
    english: "Accepted",
    arabic: "مقبولة",
    tone: "success",
  },
  {
    entity: "invitation",
    state: "expired",
    english: "Expired",
    arabic: "منتهية",
    tone: "muted",
  },
  {
    entity: "invitation",
    state: "revoked",
    english: "Revoked",
    arabic: "ملغاة",
    tone: "muted",
  },
] as const satisfies readonly ExpectedStatus[];
